trigger:
  branches:
    include:
    - blazor-*
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: secrets
  - group: defaults

steps:

- task: UseDotNet@2
  displayName: Install dotnet 8 SDK
  inputs:
    version: '8.x'
    packageType: sdk

- script: |
    dotnet build ./src/Piral.Blazor.Core --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER
    dotnet build ./src/Piral.Blazor.Utils --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER
    dotnet build ./src/Piral.Blazor.Analyzer --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER
    dotnet build ./src/Piral.Blazor.Tools --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER
    dotnet build ./src/Piral.Blazor.DevServer --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER
  displayName: 'Build Assemblies (Pre)'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/blazor-'))

- script: |
    dotnet build ./src/Piral.Blazor.Core --configuration $(buildConfiguration)
    dotnet build ./src/Piral.Blazor.Utils --configuration $(buildConfiguration)
    dotnet build ./src/Piral.Blazor.Analyzer --configuration $(buildConfiguration)
    dotnet build ./src/Piral.Blazor.Tools --configuration $(buildConfiguration)
    dotnet build ./src/Piral.Blazor.DevServer --configuration $(buildConfiguration)
  displayName: 'Build Assemblies'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- script: |
    rm ~/.nuget/packages/microsoft.aspnetcore.components/8.0.1/lib/net8.0/Microsoft.AspNetCore.Components.dll
    cp tools/Microsoft.AspNetCore.Components.dll ~/.nuget/packages/microsoft.aspnetcore.components/8.0.1/lib/net8.0/Microsoft.AspNetCore.Components.dll
  displayName: 'Change GAC'

- script: |
    dotnet build tests
    dotnet test tests
  displayName: 'Run Tests'

- script: |
    cd ./src/Piral.Blazor.Core
    export TARGET_VERSION=`node -e 'console.log(require("./obj/project.assets.json").project.version)'`
    export NPM_TOKEN=$(npmToken)
    dotnet build -c Release
    dotnet publish -c Release --output ../../dist/release
    dotnet build -c Debug
    dotnet publish -c Debug --output ../../dist/debug -p:CopyOutputSymbolsToPublishDirectory=true
    cd ../../dist
    cp ../template/* .
    cp ../LICENSE .
    npm version $TARGET_VERSION
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    echo always-auth=true >> ~/.npmrc
    cd ..
  displayName: 'Prepare NPM Package'

- script: |
    cd dist
    sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.$BUILD_BUILDNUMBER/" ./package.json;
    cat ~/.npmrc
    npm publish --tag next
    cd ..
  displayName: 'Publish Pre-Package on NPM'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/blazor-'))

- script: |
    cd dist
    npm publish --tag latest
    cd ..
  displayName: 'Publish Package on NPM'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- script: rm -rf dist
  displayName: 'Reset Output'

- script: |
    dotnet pack ./src/Piral.Blazor.Core --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
    dotnet pack ./src/Piral.Blazor.Utils --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
    dotnet pack ./src/Piral.Blazor.Template --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
    dotnet pack ./src/Piral.Blazor.Analyzer --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
    dotnet pack ./src/Piral.Blazor.Tools --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
    dotnet pack ./src/Piral.Blazor.DevServer --configuration $(buildConfiguration) --version-suffix pre.$BUILD_BUILDNUMBER --output ./dist
  displayName: 'Pack Assemblies (Pre)'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/blazor-'))

- script: |
    dotnet pack ./src/Piral.Blazor.Core --configuration $(buildConfiguration) --output ./dist
    dotnet pack ./src/Piral.Blazor.Utils --configuration $(buildConfiguration) --output ./dist
    dotnet pack ./src/Piral.Blazor.Template --configuration $(buildConfiguration) --output ./dist
    dotnet pack ./src/Piral.Blazor.Analyzer --configuration $(buildConfiguration) --output ./dist
    dotnet pack ./src/Piral.Blazor.Tools --configuration $(buildConfiguration) --output ./dist
    dotnet pack ./src/Piral.Blazor.DevServer --configuration $(buildConfiguration) --output ./dist
  displayName: 'Pack Assemblies'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- task: NuGetCommand@2
  displayName: 'Publish Packages on NuGet'
  inputs:
    command: 'push'
    packagesToPush: 'dist/*.nupkg'
    publishFeedCredentials: 'nuget'
    nuGetFeedType: 'external'
